gregcusack/solana

gossip-only/src/gossip-only.sh, gossip-only/src/main.rs, net/net-gossip.sh, net/remote/remote-gossip-node.sh
=> Gossip Only on GCE. back n number of gossip instances per node

gossip-only/src/gossip-only.sh, gossip-only/src/main.rs, net/net-gossip.sh, net/remote/remote-gossip-node.sh
=> Revert "Gossip Only on GCE. back n number of gossip instances per node"

net/k8s-cluster/src/genesis.rs, net/k8s-cluster/src/main.rs
=> add in validator accounts into genesis

net/k8s-cluster/README.md, net/k8s-cluster/src/docker.rs, net/k8s-cluster/src/genesis.rs, net/k8s-cluster/src/kubernetes.rs, net/k8s-cluster/src/lib.rs, net/k8s-cluster/src/main.rs
Issue pushing and pulling docker images
Assume registry auth already setup. Fails if not logged in
Fixes #
=> Solana k8s cluster genesis

net/k8s-cluster/src/docker.rs, net/k8s-cluster/src/genesis.rs, net/k8s-cluster/src/kubernetes.rs, net/k8s-cluster/src/lib.rs, net/k8s-cluster/src/main.rs
1) unused code
2) secret that relied on auth for docker registry
1) one replicaset/service per validator
2) rm unused code
3) rm secret for docker registry
4) change up flags
Fixes #
=> Solana k8s cluster dev

net/k8s-cluster/src/kubernetes.rs, net/k8s-cluster/src/main.rs
pods have no access to their keys
mount account keys into each corresponding pod
Fixes #
=> mount account keys into each validator pod

net/k8s-cluster/src/genesis.rs, net/k8s-cluster/src/kubernetes.rs, net/k8s-cluster/src/main.rs, net/k8s-cluster/src/scripts/bootstrap-startup-script.sh, net/k8s-cluster/src/scripts/decode-accounts.sh, net/k8s-cluster/src/scripts/validator-startup-script.sh
1) nodes using wrong version of docker container
2) genesis creation failing with non-bootstrap validator accounts inserted
3) validators failing on deployment -> dns error, try to recreate vote accounts, fails
1) change pull policy to always
2) only insert bootstrap accounts and have other validators request new vote accounts and sol
3) add a retry in case dns fails or faucet is busy. 
Fixes #
=> Solana k8s cluster working runtime

net/k8s-cluster/src/genesis.rs, net/k8s-cluster/src/main.rs
need to add in `fetch-spl.sh` and `spl-genesis-args.sh` into genesis as done in `setup.sh` called by `net.sh` script
added in `fetch-spl.sh` call and `spl-genesis-args` addition to genesis
Fixes #
=> pull spl-genesis-args via call to fetch-spl.sh

net/k8s-cluster/README.md, net/k8s-cluster/src/genesis.rs, net/k8s-cluster/src/main.rs
=> add in command line args for genesis config

k8s-cluster/src/genesis.rs, k8s-cluster/src/kubernetes.rs, k8s-cluster/src/main.rs, k8s-cluster/src/scripts/decode-accounts.sh
add in spl support
fix bug in taring genesis for config map
Fixes #
=> add in spl support

k8s-cluster/src/kubernetes.rs
needed some refactor
refactor. this is actually a PR that represents more than what it shoes. I accidentally just pushed merged stuff into k8s-cluster-official.
See here: https://github.com/gregcusack/solana/commits/k8s-cluster-official
commits: ed125fd -> 8863256
Fixes #
=> K8s cluster official refactor

Cargo.lock, k8s-cluster/Cargo.toml, k8s-cluster/src/genesis.rs, k8s-cluster/src/kubernetes.rs, k8s-cluster/src/main.rs, k8s-cluster/src/scripts/bootstrap-startup-script.sh
just need to add additional validator args
Fixes #
=> add in additional args for validator config

k8s-cluster/src/docker.rs, k8s-cluster/src/genesis.rs, k8s-cluster/src/kubernetes.rs, k8s-cluster/src/ledger_helper.rs, k8s-cluster/src/main.rs, k8s-cluster/src/scripts/decode-accounts.sh, validator/src/cli.rs
too big of files required to mount as config map. so we are just going to bake it into docker. other solutions could be done but are too complicated imo
Fixes #
=> bake genesis into docker

k8s-cluster/src/kubernetes.rs, k8s-cluster/src/ledger_helper.rs, k8s-cluster/src/main.rs
run scipts to format and clean up unused variables/imports
Fixes #
=> clean up unused vars

k8s-cluster/README.md, k8s-cluster/src/kubernetes.rs, k8s-cluster/src/main.rs, k8s-cluster/src/scripts/bootstrap-startup-script.sh, k8s-cluster/src/scripts/validator-startup-script.sh
=> rm default --require-tower. 

ci/stable/run-partition.sh, ci/test-stable.sh, scripts/coverage-in-disk.sh, scripts/coverage.sh
forgot i had removed solana-k8s-cluster from ci. so adding that back in.
Fixes #
=> rm solana-k8s-cluster exclusion from ci

k8s-cluster/src/lib.rs
=> fix cast to usize twice

Cargo.lock, programs/sbf/Cargo.lock
cherry pick https://github.com/solana-labs/solana/pull/34816. addresses h2 security vuln
=> Kco cherry pick h2 update

k8s-cluster/src/kubernetes.rs, k8s-cluster/src/main.rs
bench-tps client has very low TPS when validators are deployed in various geographic regions. 
There is a chance this could be fixed with a bench-tps receive window update. but unclear. 
Add in `--confine-to-single-region` flag to deploy in a single region. currently its just HongKong for now. 
default is deploy in multiple regions as usual
=> add ability to deploy in singular region

k8s-cluster/src/kubernetes.rs
=> fix bug for mixed deployment
